behaviors:
  Huggy:
    even_checkpoints: true
    hyperparameters:
      batch_size: 2048
      beta: 0.0001
      buffer_size: 20480
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 3
    keep_checkpoints: 10
    max_steps: 2000000
    network_settings:
      hidden_units: 512
      normalize: true
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    summary_freq: 10000
    threaded: true
    time_horizon: 1000
    trainer_type: ppo
